import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });

const MainBox = styled.div`
  width: 100%;
  height: 100%;
  background-image: url("/nati.jpg");
  background-repeat: no-repeat;
  background-position: right;
  background-color: #4d90a7;
  background-blend-mode: luminosity;
  background-size: 30%;
`;

const Text = styled.p`
  padding: 0;
  margin: 0;
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Netanel Halevi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainBox>
        <Text>היי אני רואה שמצאת את המודעה שלי</Text>
        <Text>
          אז כמו שבטח כבר ראיתם והבנתם, אני מורה פרטי, יש לי ניסיון בלימוד ילדים מבוגרים ונוער
        </Text>
        <Text>אז מצורף באתר זה כל מיני פרטים עליי ומקום ליצירת קשר</Text>
        <Link href={"/chat"}>ליצירת קשר בתוך האתר</Link>
        <Text>Whatsappp icon</Text>
        <Text>Discord</Text>
        <Text>Gmail</Text>
      </MainBox>
    </>
  );
}
